// Generated by CoffeeScript 1.6.2
(function() {
  'use strict';
  var latLngFromLl, llFromLatLng, mapMarkersPath, mapMaxZoom, spritesPath,
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  llFromLatLng = function(latLng) {
    return latLng.lat + ',' + latLng.lng;
  };

  latLngFromLl = function(ll) {
    var llSplit;

    llSplit = ll.split(',');
    return {
      lat: llSplit[0],
      lng: llSplit[1]
    };
  };

  spritesPath = 'img/map/sprites/';

  mapMarkersPath = 'img/map/markers/small/white/numbers/';

  mapMaxZoom = 19;

  angular.module('ofApp').controller('PlcsCtrl', [
    '$rootScope', '$scope', '$location', '$routeParams', '$cookies', 'Restangular', '$timeout', '$log', '$anchorScroll', 'GoogleMap', function($rootScope, $scope, $location, $routeParams, $cookies, Restangular, $timeout, $log, $anchorScroll, GoogleMap) {
      var Bdys, Plcs, defaultRouteArgs, gmap, googleMaps, map, qry;

      gmap = GoogleMap;
      googleMaps = google.maps;
      map = gmap.map;
      defaultRouteArgs = {
        ll: '9.971365509675179,-84.16658163070679',
        cngSlug: 'crherbs',
        cngAreaSlug: 'br',
        cngAreaTerrSlug: 'brr06',
        q: '',
        sort: 'bdry,w',
        filter: 'filtBdyId:crherbs',
        z: 17,
        pp: 5,
        pg: 5
      };
      $scope.items = [];
      $scope.lastItemsWithInfo = null;
      $scope.maxId = null;
      $scope.q = $routeParams.q || defaultRouteArgs.q;
      $scope.ll = $routeParams.ll || defaultRouteArgs.ll;
      $scope.z = parseInt($routeParams.z, 10) || defaultRouteArgs.z;
      $scope.pp = $routeParams.pp || defaultRouteArgs.pp;
      $scope.pg = $routeParams.pg || defaultRouteArgs.pg;
      $scope.sort = $routeParams.sort || defaultRouteArgs.sort;
      $scope.media = $routeParams.media || '';
      $rootScope.printView = $scope.printView = $routeParams.media === 'prn';
      $scope.args = defaultRouteArgs;
      $rootScope.filtBdyId = $scope.filtBdyId = null;
      $rootScope.editingBdy = false;
      $rootScope.bdysLoaded = false;
      $rootScope.selectedItemIndex = gmap.selectedItem = gmap.selectedItemIndex = -1;
      $scope.bdyViews = {
        crherbs: [
          {
            nam: 'Main',
            zoom: 14,
            llCenter: '9.976819295953407,-84.16194130521517',
            mapTypeId: 'hybrid'
          }
        ],
        crherbsbr: [
          {
            nam: 'Main',
            zoom: 15,
            llCenter: '9.971071018203258,-84.15988136869173',
            mapTypeId: 'hybrid'
          }
        ],
        crherbsbrr01: [
          {
            nam: 'Main',
            zoom: 17,
            llCenter: '9.973437968382253,-84.16134049039584',
            mapTypeId: 'hybrid',
            notes: [
              {
                title: 'Direcciónes a este territorio',
                note: 'saliendo del Salon del Reino de los Testigos de Jehovah, dobla  a la derecha y continuar al sur 600 mtrs, al final de la calle dobla a la izquierda,  en el primer semaforo dobla a la derecha, continuar hasta que llegar a la entradad de Bosques de Dona Rosa y entrar doblando a la derecha, coja la proxima derecha y la primera casa esta 100 metros mano izquierda'
              }
            ]
          }
        ],
        crherbsbrr02: [
          {
            nam: 'Main',
            zoom: 17,
            llCenter: '9.97349638016292,-84.16631358847928',
            mapTypeId: 'hybrid',
            notes: [
              {
                title: 'Direcciónes a este territorio',
                note: 'saliendo del Salon del Reino de los Testigos de Jehovah, dobla  a la derecha y continuar al sur 600 mtrs, al final de la calle dobla a la izquierda,  en el primer semaforo dobla a la derecha, continuar hasta que llegar a la entradad de Bosques de Dona Rosa y entrar doblando a la derecha, coja la proxima derecha y la primera casa esta 100 metros mano izquierda'
              }
            ]
          }
        ],
        crherbsbrr03: [
          {
            nam: 'Main',
            zoom: 18,
            llCenter: '9.973667700855833,-84.16967939293744',
            mapTypeId: 'hybrid',
            notes: [
              {
                title: 'Direcciónes a este territorio',
                note: 'saliendo del Salon del Reino de los Testigos de Jehovah, dobla  a la derecha y continuar al sur 600 mtrs, al final de la calle dobla a la izquierda,  en el primer semaforo dobla a la derecha, continuar hasta que llegar a la entradad de Bosques de Dona Rosa y entrar doblando a la derecha, coja la proxima derecha y la primera casa esta 100 metros mano izquierda'
              }
            ]
          }
        ],
        crherbsbrr04: [
          {
            nam: 'Main',
            zoom: 18,
            llCenter: '9.971095930944049,-84.16924278118506',
            mapTypeId: 'hybrid',
            notes: [
              {
                title: 'Direcciónes a este territorio',
                note: 'saliendo del Salon del Reino de los Testigos de Jehovah, dobla  a la derecha y continuar al sur 600 mtrs, al final de la calle dobla a la izquierda,  en el primer semaforo dobla a la derecha, continuar hasta que llegar a la entradad de Bosques de Dona Rosa y entrar doblando a la derecha, coja la proxima derecha y la primera casa esta 100 metros mano izquierda'
              }
            ]
          }
        ],
        crherbsbrr05: [
          {
            nam: 'Main',
            zoom: 18,
            llCenter: '9.97113872118877,-84.16887763435983',
            mapTypeId: 'hybrid',
            notes: [
              {
                title: 'Direcciónes a este territorio',
                note: 'saliendo del Salon del Reino de los Testigos de Jehovah, dobla  a la derecha y continuar al sur 600 mtrs, al final de la calle dobla a la izquierda,  en el primer semaforo dobla a la derecha, continuar hasta que llegar a la entradad de Bosques de Dona Rosa y entrar doblando a la derecha, coja la proxima derecha y la primera casa esta 100 metros mano izquierda'
              }
            ]
          }
        ],
        crherbsbrr06: [
          {
            nam: 'Main',
            zoom: 18,
            llCenter: '9.96906003005786,-84.16883676999466',
            mapTypeId: 'hybrid',
            notes: [
              {
                title: 'Direcciónes a este territorio',
                note: 'saliendo del Salon del Reino de los Testigos de Jehovah, dobla  a la derecha y continuar al sur 600 mtrs, al final de la calle dobla a la izquierda,  en el primer semaforo dobla a la derecha, continuar hasta que llegar a la entradad de Bosques de Dona Rosa y entrar doblando a la derecha, coja la proxima derecha y la primera casa esta 100 metros mano izquierda'
              }
            ]
          }, {
            nam: 'E',
            zoom: 19,
            llCenter: '9.969028329520771,-84.16865974419967',
            mapTypeId: 'hybrid'
          }, {
            nam: 'W',
            zoom: 19,
            llCenter: '9.969178907047947,-84.16866779082672',
            mapTypeId: 'hybrid'
          }
        ],
        crherbsbrr07: [
          {
            nam: 'Main',
            zoom: 18,
            llCenter: '9.967435883191067,-84.16807573414316',
            mapTypeId: 'hybrid',
            notes: [
              {
                title: 'Direcciónes a este territorio',
                note: 'saliendo del Salon del Reino de los Testigos de Jehovah, dobla  a la derecha y continuar al sur 600 mtrs, al final de la calle dobla a la izquierda,  en el primer semaforo dobla a la derecha, continuar hasta que llegar a la entradad de Bosques de Dona Rosa y entrar doblando a la derecha, coja la proxima derecha y la primera casa esta 100 metros mano izquierda'
              }
            ]
          }
        ],
        crherbsbrr08: [
          {
            nam: 'Main',
            zoom: 18,
            llCenter: '9.967593806754337,-84.16492581199572',
            mapTypeId: 'hybrid',
            notes: [
              {
                title: 'Direcciónes a este territorio',
                note: 'saliendo del Salon del Reino de los Testigos de Jehovah, dobla  a la derecha y continuar al sur 600 mtrs, al final de la calle dobla a la izquierda,  en el primer semaforo dobla a la derecha, continuar hasta que llegar a la entradad de Bosques de Dona Rosa y entrar doblando a la derecha, coja la proxima derecha y la primera casa esta 100 metros mano izquierda'
              }
            ]
          }
        ],
        crherbsbrr09: [
          {
            nam: 'Main',
            zoom: 18,
            llCenter: '9.969137449721174,-84.16503919625961',
            mapTypeId: 'hybrid',
            notes: [
              {
                title: 'Direcciónes a este territorio',
                note: 'saliendo del Salon del Reino de los Testigos de Jehovah, dobla  a la derecha y continuar al sur 600 mtrs, al final de la calle dobla a la izquierda,  en el primer semaforo dobla a la derecha, continuar hasta que llegar a la entradad de Bosques de Dona Rosa y entrar doblando a la derecha, coja la proxima derecha y la primera casa esta 100 metros mano izquierda'
              }
            ]
          }, {
            nam: 'NE',
            zoom: 19,
            llCenter: '9.969412187521936,-84.1647307422229',
            mapTypeId: 'hybrid'
          }, {
            nam: 'SW',
            zoom: 19,
            llCenter: '9.968801952286398,-84.1655944135257',
            mapTypeId: 'hybrid'
          }
        ],
        crherbsbrr10: [
          {
            nam: 'Main',
            zoom: 18,
            llCenter: '9.970525510722636,-84.16511999919874',
            mapTypeId: 'hybrid',
            notes: [
              {
                title: 'Direcciónes a este territorio',
                note: 'saliendo del Salon del Reino de los Testigos de Jehovah, dobla  a la derecha y continuar al sur 600 mtrs, al final de la calle dobla a la izquierda,  en el primer semaforo dobla a la derecha, continuar hasta que llegar a la entradad de Bosques de Dona Rosa y entrar doblando a la derecha, coja la proxima derecha y la primera casa esta 100 metros mano izquierda'
              }
            ]
          }, {
            nam: 'NW',
            zoom: 19,
            llCenter: '9.970512302225993,-84.1655813391493',
            mapTypeId: 'hybrid'
          }, {
            nam: 'E',
            zoom: 19,
            llCenter: '9.970916482013722,-84.16447090461713',
            mapTypeId: 'hybrid'
          }
        ],
        crherbsbrr11: [
          {
            nam: 'Main',
            zoom: 18,
            llCenter: '9.970053746032534,-84.16725222757447',
            mapTypeId: 'hybrid',
            notes: [
              {
                title: 'Direcciónes a este territorio',
                note: 'saliendo del Salon del Reino de los Testigos de Jehovah, dobla  a la derecha y continuar al sur 600 mtrs, al final de la calle dobla a la izquierda,  en el primer semaforo dobla a la derecha, continuar hasta que llegar a la entradad de Bosques de Dona Rosa y entrar doblando a la derecha, coja la proxima derecha y la primera casa esta 100 metros mano izquierda'
              }
            ]
          }, {
            nam: 'N',
            zoom: 19,
            llCenter: '9.970510760384416,-84.16725222757447',
            mapTypeId: 'hybrid'
          }, {
            nam: 'S',
            zoom: 19,
            llCenter: '9.969612581282494,-84.16717712572205',
            mapTypeId: 'hybrid'
          }
        ]
      };
      Bdys = Restangular.all('bdys');
      Plcs = Restangular.all('plcs');
      if (!$routeParams.sort) {
        $routeParams.sort = defaultRouteArgs.sort;
      }
      $rootScope.returnRoute = $location.$$url;
      $scope.location = $location;
      $scope.routeParams = $routeParams;
      $rootScope.filtBdyId = $scope.filtBdyId = $routeParams.filtBdyId;
      console.log('filtBdyId', $rootScope.filtBdyId);
      $rootScope.$watch('selectedItemIndex', function(newValue) {
        $scope.selectedItem = $rootScope.selectedItem;
        return $rootScope.selectedItemIndex = $scope.selectedItemIndex = newValue;
      });
      $scope.togglePrintView = function() {
        $rootScope.printView = $scope.printView = !$scope.printView;
        if ($scope.printView) {
          console.log('PrintView Set On');
          return $location.search('media', 'prn');
        } else {
          console.log('PrintView Set On');
          return $location.search('media', '');
        }
      };
      gmap.icon = function(item) {
        if ($scope.printView) {
          return $scope.mkrIcon2(item.mkrNo, item.mkrState);
        } else {
          return $scope.mkrIcon(item.mkrNo, item.mkrState);
        }
      };
      $scope.itemMkrClick = function(index) {
        var pt;

        $rootScope.selectedItemIndex = gmap.selectedItemIndex = $scope.selectedItemIndex = index;
        $rootScope.selectedItem = gmap.selectedItem = $scope.items[index];
        map.setZoom(mapMaxZoom);
        if ($scope.items[index].pt) {
          $rootScope.selectedItemIndex = gmap.selectedItemIndex = $scope.selectedItemIndex = -1;
          pt = $scope.items[index].pt;
          $scope.ll = llFromLatLng(pt);
          map.setCenter(new google.maps.LatLng(pt[0], pt[1]));
        }
        $location.hash('top');
        return $anchorScroll();
      };
      $scope.doSearch = function() {
        var args, errorCallback, i, plcIds, q, quickFindPlcIds, whereParts;

        if ($rootScope.editingBdy) {
          return;
        }
        gmap.removeMkrs();
        if (((typeof $routeParams.filtBdyId === 'boolean' || !$routeParams.filtBdyId) && !$scope.q) || (typeof $routeParams.filtBdyId === 'boolean' && !$scope.q)) {
          return;
        }
        args = {};
        q = $scope.q;
        whereParts = {};
        if (typeof $routeParams.filtBdyId !== 'boolean' && $routeParams.filtBdyId) {
          whereParts.bdry = $routeParams.filtBdyId;
        }
        quickFindPlcIds = q.match(/qp\w+/g);
        if (quickFindPlcIds) {
          plcIds = [];
          i = 0;
          while (i < quickFindPlcIds.length) {
            console.log(quickFindPlcIds[i]);
            plcIds.push(quickFindPlcIds[i].substr(2));
            ++i;
          }
          whereParts.id = {
            $in: plcIds
          };
          q = q.replace(/qp\w+\s*/g, '');
        }
        if (q) {
          whereParts.dNam = {
            $regex: q,
            $options: 'i'
          };
        }
        if (whereParts) {
          args.where = JSON.stringify(whereParts);
        }
        if ($routeParams.sort) {
          args.sort = $routeParams.sort;
        }
        return Plcs.getList(args, {
          'Authentication-Token': $rootScope.tkn
        }).then((function(items) {
          var item, mkrNo, _i, _len, _ref;

          mkrNo = 1;
          _ref = items._items;
          for (i = _i = 0, _len = _ref.length; _i < _len; i = ++_i) {
            item = _ref[i];
            items._items[i].patch = $scope.patch;
            delete items._items[i].mkrNo;
            if (item.typ !== 'ref') {
              items._items[i].mkrNo = mkrNo;
              mkrNo += 1;
            }
            if (item.pt && parseInt($routeParams.z, 10) > 16) {
              items._items[i].mapMkr = gmap.addPlcMkr(map, item);
            }
          }
          $rootScope.items = $scope.items = items._items;
          $scope.bdy = $scope.bdyViews[item.bdry][0];
          $scope.bdy.totalDoors = mkrNo - 1;
          if ($scope.q) {
            return $location.search('q', $scope.q);
          }
        }), errorCallback = function() {
          return console.log('Oops error from server :(');
        });
      };
      $scope.saveBdy = function(bdyKey) {
        var bdy;

        bdy = $rootScope.bdys[bdyKey];
        bdy.poly.setEditable(false);
        return $rootScope.editingBdy = $scope.editingBdy = false;
      };
      $scope.editBdy = function(bdyKey) {
        var bdy;

        console.log('editBdy key:', bdyKey);
        bdy = $rootScope.bdys[bdyKey];
        bdy.poly.setEditable(true);
        return $rootScope.editingBdy = $scope.editingBdy = true;
      };
      $scope.showBdyLabels = function() {
        var bdy, fontSize, lbl, mapLabel, maxZoom, minZoom, slug, strokeColor, x, zIndex, _ref, _results;

        _ref = $scope.bdys;
        _results = [];
        for (slug in _ref) {
          bdy = _ref[slug];
          minZoom = bdy.zoom;
          if (bdy.typ === "congAreaResidentialTerr") {
            strokeColor = '#98F5FF';
            fontSize = 12;
            lbl = bdy.nam.split('#')[1];
            minZoom = 15;
            maxZoom = 17;
            zIndex = 10 + 99999;
          } else if (bdy.typ === "congArea") {
            strokeColor = '#FF82AB';
            fontSize = 16;
            lbl = bdy.nam;
            minZoom = 14;
            maxZoom = 17;
            zIndex = 20 + 99999;
          } else if (bdy.typ === "cong") {
            strokeColor = 'white';
            fontSize = 25;
            lbl = bdy.nam;
            minZoom = 13;
            maxZoom = 17;
            zIndex = 30 + 99999;
          } else {
            strokeColor = 'white';
            fontSize = 20;
            lbl = bdy.nam;
            minZoom = 1;
            maxZoom = 20;
            zIndex = 1000;
          }
          mapLabel = new MapLabel({
            minZoom: minZoom,
            maxZoom: maxZoom,
            strokeColor: strokeColor,
            text: lbl,
            position: new google.maps.LatLng(bdy.ptCenter[0], bdy.ptCenter[1]),
            map: map,
            fontSize: fontSize,
            zIndex: zIndex
          });
          _results.push(x = 0);
        }
        return _results;
      };
      $scope.loadBdys = function() {
        var errorCallback;

        return Bdys.getList({
          sort: 'typ,slug'
        }, {
          'Authentication-Token': $rootScope.tkn
        }).then((function(items) {
          var bdy, bdys, filtBdys, i, item, _i, _len, _ref;

          bdys = {};
          filtBdys = [];
          _ref = items._items;
          for (i = _i = 0, _len = _ref.length; _i < _len; i = ++_i) {
            item = _ref[i];
            bdy = {
              slug: item.slug,
              nam: item.nam,
              typ: item.typ,
              ptCenter: [item.ptCenter[0], item.ptCenter[1]],
              zoom: 18,
              mapTypeId: 'hybrid'
            };
            if (item.typ === "congAreaResidentialTerr") {
              bdy.zoom = 18;
            } else if (item.typ === "congArea") {
              bdy.zoom = 15;
            } else if (item.typ === "cong") {
              bdy.zoom = 14;
            } else {
              bdy.zoom = 12;
            }
            bdys[item.slug] = bdy;
            filtBdys.push({
              slug: item.slug,
              nam: item.nam
            });
          }
          $scope.bdys = bdys;
          $scope.filtBdys = filtBdys;
          return $scope.showBdyLabels();
        }), errorCallback = function() {
          return console.log('Oops error from server :(');
        });
      };
      $scope.loadBdyPolys = function() {
        var errorCallback;

        return Bdys.getList(null, {
          'Authentication-Token': $rootScope.tkn
        }).then((function(items) {
          var bdy, bdys, i, item, _i, _len, _ref;

          bdys = {};
          _ref = items._items;
          for (i = _i = 0, _len = _ref.length; _i < _len; i = ++_i) {
            item = _ref[i];
            bdy = item;
            bdy.bdyPoly = gmap.addBdy(map, bdy);
            bdys[item.slug] = bdy;
          }
          return $rootScope.bdysLoaded = true;
        }), errorCallback = function() {
          return console.log('Oops error from server :(');
        });
      };
      $scope.patch = function(_id, data) {
        var Plc, errorCallback;

        Plc = Restangular.one('plcs', _id);
        return Plc.customPUT(null, null, null, data).then((function(itemUpdated) {
          return console.log('success!');
        }), errorCallback = function() {
          return console.log('Oops error from server :(');
        });
      };
      $scope.$watch('z', function(newValue) {
        $location.search('z', newValue);
        return $scope.z = parseInt(newValue, 10);
      });
      $scope.$watch('filtBdyId', function(newValue) {
        var bdy, llCenter, ptCenter;

        $location.search('filtBdyId', newValue);
        $rootScope.filtBdyId = $scope.filtBdyId = newValue;
        bdy = '';
        if (newValue && typeof newValue === 'string' && $routeParams.filtBdyId !== newValue) {
          bdy = $scope.bdys[newValue];
          ptCenter = bdy.ptCenter;
          map.setCenter(new google.maps.LatLng(ptCenter[0], ptCenter[1]));
          llCenter = latLngFromLl($scope.bdyViews[newValue][0].llCenter);
          map.setCenter(new google.maps.LatLng(llCenter.lat, llCenter.lng));
          map.setZoom($scope.bdyViews[newValue][0].zoom);
          map.setZoom(bdy.zoom);
          map.setMapTypeId(bdy.mapTypeId);
          $rootScope.filtBdyId = $scope.filtBdyId = newValue;
          $routeParams.filtBdyId = newValue;
          $rootScope.title = $scope.title = $routeParams.title = bdy.nam;
          return console.log('newValue inside', newValue, bdy.nam);
        } else if ($routeParams.filtBdyId !== newValue) {
          console.log('newValue', '');
          $rootScope.title = $scope.title = '';
          return $routeParams.title = '';
        }
      });
      $scope.$watch('routeParams', (function(newVal, oldVal) {
        if (!$rootScope.editingBdy) {
          return angular.forEach(newVal, function(v, k) {
            if (k !== 'where') {
              $scope[k] = v;
              return $location.search(k, v);
            }
          });
        }
      }), true);
      qry = {};
      $scope.doClear = function() {
        $scope.q = $scope.location.q = $scope.routeParams.q = defaultRouteArgs.q;
        return $scope.doSearch();
      };
      $scope.moveDown = function($index) {
        var Plc, confirmMove, data, errorCallback, itemFrom, itemNext, newValueForNext_w;

        confirmMove = confirm('Move Down?');
        if (!confirmMove) {
          return;
        }
        itemFrom = $scope.items[$index];
        itemNext = $scope.items[$index + 1];
        if ($index === 0) {
          newValueForNext_w = itemFrom.w - 1.00000001;
        } else {
          newValueForNext_w = itemFrom.w - ((itemFrom.w - $scope.items[$index - 1].w) / 2);
        }
        data = JSON.stringify({
          actions: {
            $set: {
              flds: {
                w: newValueForNext_w
              }
            }
          }
        });
        Plc = Restangular.one('plcs', itemNext._id);
        return Plc.customPUT(null, null, null, data).then((function(itemChanged) {
          return $scope.doSearch();
        }), errorCallback = function() {
          return console.log('Oops error from server :(');
        });
      };
      $scope.moveUp = function($index) {
        var Plc, confirmMove, data, errorCallback, itemFrom, itemPrevious, newValueForPrevious_w;

        confirmMove = confirm('Move up?');
        if (!confirmMove) {
          return;
        }
        itemFrom = $scope.items[$index];
        itemPrevious = $scope.items[$index - 1];
        if ($index === $scope.items.length - 1) {
          newValueForPrevious_w = itemFrom.w + 1.00000001;
        } else if ($index === 0) {
          newValueForPrevious_w = itemFrom.w - 1.00000001;
        } else {
          newValueForPrevious_w = itemFrom.w + (($scope.items[$index + 1].w - itemFrom.w) / 2);
        }
        data = JSON.stringify({
          actions: {
            $set: {
              flds: {
                w: newValueForPrevious_w
              }
            }
          }
        });
        Plc = Restangular.one('plcs', itemPrevious._id);
        return Plc.customPUT(null, null, null, data).then((function(itemChanged) {
          return $scope.doSearch();
        }), errorCallback = function() {
          return console.log('Oops error from server :(');
        });
      };
      $scope.insertAfter = function($index) {
        var blankItem, confirmInsert, data, itemFrom;

        confirmInsert = confirm('Insert a new place?');
        if (!confirmInsert) {
          return;
        }
        itemFrom = $scope.items[$index];
        blankItem = {
          nam: 'Nuevo lugar en blanco.',
          bdry: itemFrom.bdry
        };
        if ($index === $scope.items.length - 1) {
          blankItem.w = itemFrom.w + 1.00000001;
        } else {
          blankItem.w = itemFrom.w + (($scope.items[$index + 1].w - itemFrom.w) / 2);
        }
        data = 'doc=' + JSON.stringify(blankItem);
        Plcs = Restangular.all('plcs');
        return Plcs.post(data).then(function(itemAdded) {
          return $scope.doSearch();
        });
      };
      $scope.add = function() {
        var data;

        data = 'doc=' + JSON.stringify($scope.newItem);
        Plcs = Restangular.all('plcs');
        return Plcs.post(data).then(function(itemAdded) {
          $scope.newItem._id = itemAdded.doc._id;
          $scope.items.push($scope.newItem);
          return $scope.newItem = {};
        });
      };
      $scope.remove = function($index) {
        var Plc, confirmRemove, errorCallback, item;

        confirmRemove = confirm('Are you absolutely sure you want to delete?');
        if (confirmRemove) {
          item = $scope.items[$index];
          Plc = Restangular.one('plcs', item._id);
          return Plc.remove().then((function() {
            return $scope.doSearch();
          }), errorCallback = function() {
            console.log('Oops error from server :(');
            return $location.path('/plc/' + $routeParams.id);
          });
        }
      };
      $scope.insert = function() {
        return $location.path('/plc/insert');
      };
      $scope.edit = function($index) {
        var item;

        item = $scope.items[$index];
        return $location.path('/plc/' + item._id + '/edit');
      };
      $scope.view = function($index) {
        var item;

        item = $scope.items[$index];
        return $location.path('/plc/' + item._id);
      };
      $scope.mkrIcon = function(mkrNo, mkrState) {
        var icon, markerHeight, markerWidth, mkrStates, spriteImage, spriteX, spriteY;

        if (mkrState == null) {
          mkrState = 0;
        }
        mkrStates = ['new', 'try_1', 'try_1_contacted', 'try_2', 'try_2_contacted', 'try_3', 'try_3_contacted'];
        markerHeight = 12;
        markerWidth = null;
        spriteImage = null;
        spriteX = null;
        spriteY = null;
        if (mkrNo < 10) {
          spriteImage = spritesPath + 'sprite_1.png';
          markerWidth = 12;
          spriteX = (mkrNo - 1) * markerWidth;
          spriteY = mkrState * markerHeight;
        } else if (mkrNo < 100) {
          spriteImage = spritesPath + 'sprite_2.png';
          markerWidth = 14;
          spriteX = (mkrNo - 10) * markerWidth;
          spriteY = mkrState * markerHeight;
        } else {
          spriteImage = spritesPath + 'sprite_3.png';
          markerWidth = 18;
          spriteX = (mkrNo - 100) * markerWidth;
          spriteY = mkrState * markerHeight;
        }
        if (spriteY) {
          spriteY += 1;
        }
        if (mkrNo && mkrState > -1) {
          icon = new google.maps.MarkerImage(spriteImage, new google.maps.Size(markerWidth, 12), new google.maps.Point(spriteX, spriteY), new google.maps.Point(markerWidth / 2, markerHeight / 2));
        }
        return icon;
      };
      $scope.mkrIcon2 = function(mkrNo, mkrState) {
        var icon, iconImage, mkrHeight, mkrWidth;

        if (mkrState == null) {
          mkrState = 0;
        }
        iconImage = mapMarkersPath + mkrNo + '.png';
        mkrHeight = 12;
        if (mkrNo < 10) {
          mkrWidth = 12;
        } else if (mkrNo < 100) {
          mkrWidth = 14;
        } else {
          mkrWidth = 20;
        }
        icon = new google.maps.MarkerImage(iconImage, new google.maps.Size(mkrWidth, mkrHeight), new google.maps.Point(0, 0));
        return icon;
      };
      $scope.loadBdys();
      $scope.doSearch();
      return $scope.loadBdyPolys();
    }
  ]);

  angular.module('ofApp').controller('PlcFormCtrl', [
    '$rootScope', '$scope', '$location', '$routeParams', 'Restangular', function($rootScope, $scope, $location, $routeParams, Restangular) {
      var Plc, errorCallback, insertMode;

      insertMode = $location.$$path === '/plc/insert';
      if (insertMode) {
        $scope.mode = 'Add New';
      } else {
        $scope.mode = 'Update';
        Plc = Restangular.one('plcs', $routeParams.id);
        Plc.get().then((function(item) {
          $scope.etag = item.etag;
          $scope.dNam = item.dNam;
          $scope.item = {};
          $scope.item._id = item._id || null;
          $scope.item.bdry = item.bdry || '';
          $scope.item.nam = item.nam || '';
          $scope.item.namS = item.namS || '';
          $scope.item.typ = item.typ || '';
          $scope.item.addr = item.addr;
          $scope.item.desc = item.desc;
          $scope.item.w = item.w;
          if (typeof item.tags !== 'undefined') {
            $scope.item.tags = item.tags.join(',');
          } else {
            $scope.item.tags = '';
          }
          if (typeof item.pt !== 'undefined') {
            $scope.item.lng = item.pt[0];
            return $scope.item.lat = item.pt[1];
          }
        }), errorCallback = function() {
          return console.log('Oops error from server :(');
        });
      }
      $scope.remove = function(item) {
        var confirmRemove;

        confirmRemove = confirm('Are you absolutely sure you want to delete?');
        if (confirmRemove) {
          Plc = Restangular.one('plcs', item._id);
          return Plc.remove().then((function() {
            return $location.path('/plcs');
          }), errorCallback = function() {
            console.log('Oops error from server :(');
            return $location.path('/plc/' + $routeParams.id);
          });
        }
      };
      $scope.save = function(item) {
        var Plcs, data, error, headers;

        data = {};
        console.log('save');
        if (insertMode) {
          data = 'doc=' + JSON.stringify(item);
          Plcs = Restangular.all('plcs');
          return Plcs.post(data).then((function() {
            return window.location.href = '#' + $rootScope.returnRoute;
          }), errorCallback = function() {
            return console.log('Oops error from server :(');
          });
        } else {
          if (typeof item.tags !== 'undefined' && item.tags > '') {
            try {
              item.tags = item.tags.split(',');
            } catch (_error) {
              error = _error;
              console.log('spit error');
            }
          } else {
            item.tags = [];
          }
          if (item.typ === 'ref') {
            item.pt = [];
          }
          delete item.lat;
          delete item.lng;
          delete item._id;
          item.w += .000000001;
          data = JSON.stringify({
            actions: {
              $set: {
                flds: item
              }
            }
          });
          headers = {
            'If-Match': $scope.etag
          };
          return Plc.customPUT(null, null, null, data).then((function(itemUpdated) {
            return window.location.href = '#' + $rootScope.returnRoute;
          }), errorCallback = function() {
            return console.log('Oops error from server :(');
          });
        }
      };
      return $scope.abandonChanges = function() {
        return $location.path('/plc/' + $scope.item._id);
      };
    }
  ]);

  angular.module('ofApp').controller('PlcViewCtrl', [
    '$rootScope', '$scope', '$location', '$routeParams', 'Restangular', function($rootScope, $scope, $location, $routeParams, Restangular) {
      var Plc, errorCallback;

      Plc = Restangular.one('plcs', $routeParams.id);
      Plc.get().then((function(item) {
        $scope.item = item;
        if (__indexOf.call(item, 'pt') >= 0) {
          $scope.lng = item.pt[0];
          return $scope.lat = item.pt[1];
        }
      }), errorCallback = function() {
        return console.log('Oops error from server :(');
      });
      $scope.remove = function(item) {
        var confirmRemove;

        confirmRemove = confirm('Are you absolutely sure you want to delete?');
        if (confirmRemove) {
          Plc = Restangular.one('plcs', item._id);
          return Plc.remove().then((function() {
            return window.location.href = '#' + $rootScope.returnRoute;
          }), errorCallback = function() {
            console.log('Oops error from server :(');
            return window.location.href = '#' + $rootScope.returnRoute;
          });
        }
      };
      return $scope.edit = function(item) {
        return $location.path('/plc/' + item._id + '/edit');
      };
    }
  ]);

}).call(this);
