// Generated by CoffeeScript 1.6.2
(function() {
  'use strict';  angular.module('ofApp').factory('Auth', function(Restangular, $http, $rootScope, $location, $cookieStore) {
    var accessLevels, userRoles;

    accessLevels = routingConfig.accessLevels;
    userRoles = routingConfig.userRoles;
    $rootScope.tkn = $cookieStore.get("tkn") || "";
    $rootScope.user = $cookieStore.get("user") || {
      uNam: "",
      email: "",
      tkn: "",
      role: 6
    };
    console.log('Auth', $rootScope.user);
    $rootScope.accessLevels = accessLevels;
    $rootScope.userRoles = userRoles;
    return {
      authorize: function(accessLevel, role) {
        if (typeof role === 'undefined') {
          role = $rootScope.user.role;
        }
        return accessLevel & role;
      },
      isLoggedIn: function(user) {
        if (typeof user === 'undefined') {
          user = $rootScope.user;
        }
        user.role === userRoles.user || user.role === userRoles.admin;
        console.log('isLoggedIn', user);
        return user.role;
      },
      register: function(user, success, error) {
        return $http.post('/register', user).success(success).error(error);
      },
      login: function(user, success, error) {
        var data;

        data = 'doc=' + JSON.stringify({
          uNamOrEmail: "admin@xchg.com",
          pw: "admin"
        });
        return $http({
          method: 'POST',
          url: 'http://localhost:5000/api/users/_/login',
          data: data,
          headers: {
            'Content-Type': 'application/x-www-form-urlencoded'
          }
        }).success(function(response) {
          var u;

          console.log('login success');
          u = response.user;
          $rootScope.tkn = u.tkn;
          u.role = 'admin';
          $cookieStore.put('user', u);
          $cookieStore.put('tkn', u.tkn);
          $rootScope.user = u;
          return success(u);
        }).error(function(response) {
          return console.log(response || "Request failed");
        });
      },
      logout: function(success, error) {
        return $http.post('/logout').success(function() {
          console.log('logout');
          $rootScope.user.uNam = "";
          $rootScope.user.role = userRoles["public"];
          $location.path('/');
          return success();
        }).error(error);
      },
      accessLevels: accessLevels,
      userRoles: userRoles
    };
  });

}).call(this);
