// Generated by CoffeeScript 1.6.2
(function() {
  "use strict";  angular.module("ofApp").factory("Auth", function(Restangular, $http, $rootScope, $cookieStore) {
    var accessLevels, userRoles;

    accessLevels = routingConfig.accessLevels;
    userRoles = routingConfig.userRoles;
    if (localStorage.getItem("lsuser")) {
      $rootScope.user = JSON.parse(localStorage.getItem("lsuser"));
    }
    $rootScope.accessLevels = accessLevels;
    $rootScope.userRoles = userRoles;
    return {
      authorize: function(accessLevel, role) {
        if (role !== undefined) {
          return true;
        }
        return false;
      },
      isLoggedIn: function(user) {
        if (user === undefined) {
          user = $rootScope.user;
          return user;
        }
      },
      register: function(user, success, error) {
        return $http.post("/register", user).success(success).error(error);
      },
      login: function(user, success, error) {
        var Users;

        Users = Restangular.all("users");
        return Users.getList({
          where: JSON.stringify({
            uNam: user.username
          })
        }).then((function(items) {
          if (items._items.length) {
            user = items._items[0];
            $rootScope.user = user;
            return success(user);
          }
        }), (function(res) {
          return $location.path("/");
        }), function(err) {
          return $rootScope.error = "Failed to login";
        });
      },
      logout: function(success, error) {
        return $http.post("/logout").success(function() {
          $rootScope.user.uNam = "";
          return success();
        }).error(error);
      },
      accessLevels: accessLevels,
      userRoles: userRoles
    };
  });

}).call(this);
